### ISSUE TITLE
RQuantLib unix only

### ISSUE THREAD

**Issue by timelyportfolio** [abresler/fundManageR#1]
Is `RQuantLib` essential?  It is unix only, so `fundManageR` will not be available for Windows, and there's a lot of Windows in finance :)  This was not always the case, so I'll try to figure out when this sad moment occurred.

```
> install.packages("RQuantLib")
Installing package into ‘C:/Users/KENT/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘RQuantLib’ is not available (for R version 3.3.1)
> devtools::install_github("eddelbuettel/rquantlib")
Downloading GitHub repo eddelbuettel/rquantlib@master
from URL https://api.github.com/repos/eddelbuettel/rquantlib/zipball/master
Installing RQuantLib
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/KENT/AppData/Local/Temp/RtmpKu1bPR/devtools3f875402d1f/eddelbuettel-rquantlib-0b4ee2a"  \
  --library="C:/Users/KENT/Documents/R/win-library/3.3"  \
  --install-tests 

ERROR:  Unix-only package
* removing 'C:/Users/KENT/Documents/R/win-library/3.3/RQuantLib'
Error: Command failed (1)
```

**Comment by abresler** [comment]
Had this fear, will have to take this out

**Comment by timelyportfolio** [comment]
That would be awful.  Can you wrap this functionality in stopifnot(requireNamespace("RQuantLib"))?

**Comment by abresler** [comment]
Those functions weren't essential to the package so I took out the functions that relied on them.  Would like to see if I can find a good work around as they are just 2 functions from RQuantlib that deal with date calculations.  See if you can install now though.
