### ISSUE TITLE
curlconverter

### ISSUE THREAD

**Issue by aegerton** [abresler/fundManageR#10]
Alex, I am getting the following error message when trying to install the dependent packages;-

Warning in install.packages :
  package ‘curlconverter’ is not available (for R version 3.4.2)

And the following when subsequently trying to install fundManageR itself;-

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'curlconverter'
ERROR: lazy loading failed for package 'fundManageR'
* removing 'C:/Users/AAHE/Documents/R/win-library/3.4/fundManageR'
Installation failed: Command failed (1)

What do you suggest, please?

Tony

**Comment by soedr** [comment]
Hi @aegerton, faced same issue, but installed directly from github with `devtools::install_github("hrbrmstr/curlconverter")`. Session info below:

```> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] curlconverter_0.8.2 httr_1.3.1         

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13    digest_0.6.12   V8_1.5          withr_2.0.0     R6_2.2.2        jsonlite_1.5    git2r_0.19.0   
 [8] formatR_1.5     magrittr_1.5    stringi_1.1.5   rlang_0.1.2     curl_3.0        devtools_1.13.3 tools_3.4.2    
[15] purrr_0.2.3     compiler_3.4.2  clipr_0.3.3     memoise_1.1.0   knitr_1.17  ```

**Comment by aegerton** [comment]
Thank you @soedr.  I did also get that to work, together with a number of other dependencies that had to be installed manually.  However, I now have a more fundamental issue.  Having finally installed the fundManageR package, I have tried to run the following script

df_metrics <- fundManageR::get_tradeview_regions_metrics(regions = c("america"))

I get the following error message;-

WARNING -- this function requires Python and the requests module!!!!

Does the Package really need Python in order to run, please?

**Comment by abresler** [comment]
This API wrapper is very much under development and as the message says very clearly states:

**yes you need python and the requests module** in order to try to use this so if you want to try to use this function that is what you need to do.
