### ISSUE TITLE
issues loading fundManageR

### ISSUE THREAD

**Issue by p-will-b** [abresler/fundManageR#12]
Alex,

This package is awesome and I have used it successfully in the past. However, tonight, my attempts to re-run were unsuccessful. I have all dependent packages certainly installed and reviewed your installation instructions multiple times. 

When I  run devtools::install_github("abresler/fundManageR", force = TRUE) most of the functions appear to load fine and I can run them. However, three return the following issues:

Rd warning: C:/Users/pb/AppData/Local/Temp/RtmpW2woJz/devtoolsb3c562e4c02/abresler-fundManageR-42da486/man/get_data_adv_managers_current_period_summary.Rd:55: missing link 'get_data_adv_managers_periods_summariess'

Rd warning: C:/Users/pb/AppData/Local/Temp/RtmpW2woJz/devtoolsb3c562e4c02/abresler-fundManageR-42da486/man/get_data_adv_managers_metadata.Rd:28: missing link 'get_data_adv_managers_filing()'
    get_data_adv_managers_periods_summaries

Rd warning: C:/Users/pb/AppData/Local/Temp/RtmpW2woJz/devtoolsb3c562e4c02/abresler-fundManageR-42da486/man/get_data_finra_people.Rd:29: missing link 'get_data_finra_people()'

Any idea why this might be happening? I've tried running different (older) versions of R to solve it. No luck. I've removed and re-installed all dependencies...Not sure if you have any sense of this issue? 

Cheers and many thanks for your great work.

**Comment by abresler** [comment]
There was a spelling error in the documentation which may have caused this, try the newest version

**Comment by unrealalpha** [comment]
Still facing the same issue:

> devtools::install_github("abresler/fundManageR", force = TRUE)
Downloading GitHub repo abresler/fundManageR@master
from URL https://api.github.com/repos/abresler/fundManageR/zipball/master
Installing fundManageR
"D:/PROGRA~2/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/User/AppData/Local/Temp/Rtmp4w3ULA/devtools2f085908198d/abresler-fundManageR-e11beaf" --library="D:/Program Files/R/R-3.4.2/library" --install-tests 

* installing *source* package 'fundManageR' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'anytime'
ERROR: lazy loading failed for package 'fundManageR'
* removing 'D:/Program Files/R/R-3.4.2/library/fundManageR'

**Comment by abresler** [comment]
I dont know what to tell you unfortunately it is probably windows related

**Comment by abresler** [comment]
Install the anytime package
