### ISSUE TITLE
get_data_adv_managers_current_period_summary() dir location?

### ISSUE THREAD

**Issue by timelyportfolio** [abresler/fundManageR#4]
https://github.com/abresler/fundManageR/blob/master/R/adv_functions.R#L8779-L8780 specifies a location as default that is not available on all os.  Why not just use current directory or a temporary directory?

**Comment by abresler** [comment]
I want to let the user specify but I guess I can change the default to
current working directory.  In some cases you can be downloading gigabytes
of files and I don't want that in memory/temporary files cause it can blow
things up.  Same problem for gdeltr2 will see if I can get a fix that will
work for windows users

---

Alex Bresler
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239 (cell)

**Comment by abresler** [comment]
Does calling empty the trash work for you on Windows using the system
function?

---

Alex Bresler
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239 (cell)

**Comment by timelyportfolio** [comment]
could you just do `file_directory=getwd()`?  If huge, then you could warn or even provide a dialog to confirm the action.  If you want user to explicitly provide a location, then set `file_directory=NULL` and stop/error if not provided.

**Comment by abresler** [comment]
Bright minds think alike -- was going to try that.  Can you confirm whether calling system empty the trash works for you on a windows machine though

**Comment by abresler** [comment]
Ok I changed the syntax to let the user give a directory (set to NULL) and a folder name (set to adv_data by default) -- if both are NULL you are returned an error.  If the directory is NULL but the folder is set the folder is created in the working directory.  I like this, can you test and most importantly I want to know if the remove files and empty trash work.  Right now they are both set to TRUE but if they don't work for you I will set the default to FALSE which for now will do.

**Comment by timelyportfolio** [comment]
What is the purpose of this [line](https://github.com/abresler/fundManageR/blame/master/R/adv_functions.R#L8720)?  Best I can tell, it defeats the purpose of the `file_directory` argument.

**Comment by timelyportfolio** [comment]
I am still wondering why not use `tempdir/tempfile` for this, since `temp*` alleviates burden of keeping up with delete/empty and also more closely follows what I know as best practice in R.  It seems to me if you believe `empty_trash=T` and `remove_files=T` are good defaults, then just use `temp*` for this and let the system handle deletion and cleanup.

**Comment by abresler** [comment]
More I think about it even though for personally i don't want that I think
you are right, default action should be tmp out of safety but if loop
through say all the adv periods your memory may explode, that's the trade
off but yea better to err on the side of safety

---

Alex Bresler
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239 (cell)

**Comment by abresler** [comment]
Also Kenton can you test and see if the other workhorse function works.  It does for me but that doesn't always say much :(

```
get_data_adv_managers_filings(crd_ids = 162351, all_sections = T)
```

**Comment by abresler** [comment]
Heeded you KLR; much better protocol.  Please confirm it works.  Going to port this to gdeltr2 as well.  Also think using unlink may minimize the memory issues I was worried about. 

Tomorrow I think is time to finally announce this thing!
