### ISSUE TITLE
remove setwd('~')

### ISSUE THREAD

**Issue by timelyportfolio** [abresler/fundManageR#5]
I think there is a leftover `setwd` for local development in https://github.com/abresler/fundManageR/blob/183726bc15d368aa36c9b290cc4e606ac75dcc15/R/adv_functions.R#L8767.  I would recommend removing this as it results in unexpected and often undesired behavior.

**Comment by abresler** [comment]
Good find

---

Alex Bresler
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239 (cell)

**Comment by abresler** [comment]
Removed in 0.1.103
