### ISSUE TITLE
ERROR: dependency 'tabulizer' is not available for package 'fundManageR'

### ISSUE THREAD

**Issue by hbcondo** [abresler/fundManageR#7]
Hi, @abresler. You put a lot of work into this and I'm excited to try out the functions but when running the installation, I'm receiving the message: 

`ERROR: dependency 'tabulizer' is not available for package 'fundManageR'`

I tried installing tabulizer manually as instructed on their [GitHub page](https://github.com/ropensci/tabulizer) but can't get it to run per some of their open issues. 

Is there a way to remove the tabulizer dependency? I'm not planning on using any of the functions dependent on PDFs. Thanks!

_Note: I'm running this on a Windows 10, Visual Studio 2017 machine under the Microsoft R Client (3.3.3.0)_

**Comment by abresler** [comment]
Many of the functions require it so I need to keep this as a dependency, you may want to open issue on the tabulizer page

**Comment by hbcondo** [comment]
Thank you for your reply. There are a few open issues with Tabulizer but I was able to somehow install it individually along with some of the other dependencies.

**Comment by MikhailArkhipov** [comment]
The package is not installable from CRAN as a dependency. Installation fails in RGui, RStudio and RTVS. It has to be installed from GitHub and requires Java.
