### ISSUE TITLE
ADV Specific get_data_ Functions not working?

### ISSUE THREAD

**Issue by hbcondo** [abresler/fundManageR#8]
I'm trying some CRDs for the ADV specific get_data_ functions including the Brief Examples listed on the readme but keep receiving the following error:

`Error in mutate_impl(.data, dots) : object 'dataTable' not found
In addition: 
Warning messages:
1: Unknown column 'nameEntityManager' 
2: Unknown column 'nameSectionActual'`

Can some insight be provided on how to correctly use the `get_data_adv_` methods? Thank you.

**Comment by abresler** [comment]
Your question is unclear but all of these work for me.

```
devtools::install_github("abresler/fundManageR")
library(dplyr)
df_brochure_test <-
  fundManageR::get_data_adv_managers_brochures(entity_names = "Rockwood Capital",
                                               crd_ids = 162351)
df_brochure_test %>% 
  glimpse()

df_iapd_test <-
  fundManageR::get_data_adv_managers_filings(entity_names = "Rockwood Capital",
                                               crd_ids = 162351)

df_iapd_test %>% 
  glimpse()

df_most_recent_summary <- 
  fundManageR::get_data_adv_managers_periods_summaries(only_most_recent = TRUE)

df_most_recent_summary %>% 
  glimpse()
```

<img width="718" alt="screen shot 2017-07-03 at 10 29 07 am" src="https://user-images.githubusercontent.com/740564/27797144-823591a2-5fda-11e7-9b2c-f5e1e51d6666.png">
<img width="722" alt="screen shot 2017-07-03 at 10 29 02 am" src="https://user-images.githubusercontent.com/740564/27797142-8231c34c-5fda-11e7-812b-d8e20366abef.png">
<img width="719" alt="screen shot 2017-07-03 at 10 28 49 am" src="https://user-images.githubusercontent.com/740564/27797143-823509f8-5fda-11e7-8ac6-541c8b20ef51.png">
<img width="726" alt="screen shot 2017-07-03 at 10 28 41 am" src="https://user-images.githubusercontent.com/740564/27797145-8237da0c-5fda-11e7-8d69-764aae2b0f35.png">
