### ISSUE TITLE
Requirement not met

### ISSUE THREAD

**Issue by mcoumans** [abresler/fundManageR#9]
Package dependencies list "curlconverter".

Installation gives: 

> Warning in install.packages :
>   package ‘curlconverter’ is not available (for R version 3.4.2)

This package has been removed from CRAN.
https://cran.r-project.org/web/packages/curlconverter/index.html

**Comment by abresler** [comment]
I changed some of the dependencies around but for you to fully be able to use the package you should install for now.

```
devtools::install_github("hrbrmstr/curlconverter")
```

Restart R and then retry with the newest version of fundManageR
